### ISSUE TITLE
Argument 'workerInfo' on hook 'done' not passed

### ISSUE THREAD

**Issue by njam** [nuxt-community/nuxt-generate-cluster#15]
The third argument on the 'done' hook should be an Object called `workerInfo`, but actually I receive `undefined`.

Should be passed to [`done(workerInfo)`](https://github.com/nuxt-community/nuxt-generate-cluster/blob/91c33362bd9a441aa3a192136241ceaaf5eb8eed/lib/generate/master.js#L102), but is not.

Version: 2.3.2

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-generate-cluster/issues/c8">#c8</a>)</em></sub></div>

**Comment by njam** [comment]
@pimlie I can't find the issue template I should use for the issue. The link provided by the bot leads to a login screen. Am I missing something?

Could you reopen this ticket if you agree that it is a bug?

**Comment by pimlie** [comment]
Looks indeed like a bug, will have a look at it later this week.

(The idea behind cmty.app is that you only submit questions/issues through their community platform and not through github. It is enabled for all nuxt-community repositories)

**Comment by njam** [comment]
Works, thanks!
