### ISSUE TITLE
Error: spawn E2BIG is occurred

### ISSUE THREAD

**Issue by mankichi14** [nuxt-community/nuxt-generate-cluster#21]
Hi!
"Error: spawn E2BIG" is occurred when I do "nuxt-generate -w 4 -b"
I will generate 2864 routes.

Should I set other option?

**Comment by pimlie** [comment]
Unfortunately I havent see this error before. Have you changed any of the default settings?

Maybe you could try to lower the `workerConcurrency`. Depending on the `getconf ARG_MAX` setting of your os and how long your route paths are this could maybe result in a too large chunk?

**Comment by mankichi14** [comment]
Thank you your quick response!

I did something for check and found it's caused by a lot of files.
I reduced generate files and then it succeeded.

I hope that the nuxt-generate-cluster will able to process a lot of files because it's performance is super! I'm surprised!

**Comment by tomohiroo** [comment]
Hi.
When generating 564 paths, I've face the same error:
```
spawn E2BIG
```

I can build files on local but can't on circleci.

I tried all of below.
```
  generate: {
    workerConcurrency: 100,
    concurrency: 100,
    routes: myRoutes,
    fallback: true
  },
```
```
  generate: {
    workerConcurrency: 500,
    concurrency: 500,
    routes: myRoutes,
    fallback: true
  },
```
```
  generate: {
    workerConcurrency: 1000,
    concurrency: 1000,
    routes: myRoutes,
    fallback: true
  },
```
