### ISSUE TITLE
ERROR  Could not resolve routes, WARN  No routes so not starting workers

### ISSUE THREAD

**Issue by kyrsquir** [nuxt-community/nuxt-generate-cluster#25]
How to use this with an existing working (too slowly so I'm trying to speed things up) setup for regular `nuxt generate`? What should I pass to routes here?

nuxt.config.js:
```javascript
const axios = Axios.create({
  baseURL: process.env.API_URL
})

module.exports = {
  <...>
  generate: {
    workers: 8,
    async routes() {
      const [
        { data: authors },
        { data: yearsIssues },
        { data: issues },
        { data: articles }
      ] = await Promise.all([
        axios.get(`/all_authors_contribution`),
        axios.get(`/all_issues_by_year`),
        axios.get(`/all_issues`),
        axios.get(`/articles`)
      ])
      const authorsRoutes = authors.map(entry => ({
        route: `/authors/${entry.author.author_id}`,
        payload: entry
      }))
      const yearsRoutes = yearsIssues.map(yearIssues => ({
        route: `/archive/${yearIssues.year}`,
        payload: yearIssues.issues
      }))
      const issuesRoutes = issues.map(issue => ({
        route: `/archive/${issue.feature || issue.year}/${issue.order_within_year}`,
        payload: issue
      }))
      const articlesRoutes = articles
        .filter(article => !!article.issue)
        .map(article => ({
          route: `/archive/${article.issue.feature || article.issue.year}/${article.issue.order_within_year}/${article.section.order_within_issue}/${article.order_within_section}`,
          payload: article
        }))
      return [
        ...authorsRoutes,
        ...yearsRoutes,
        ...issuesRoutes,
        ...articlesRoutes
      ]
    },
    <...>
  }
}
```

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-generate-cluster/issues/c15">#c15</a>)</em></sub></div>

**Comment by kyrsquir** [comment]
@pimlie Please look at this as it might actually mean a bug/feature request. Shouldn't configuration which works with `nuxt generate` also pass for `nuxt-generate`?

**Comment by pimlie** [comment]
Yeah, that should just work normally. Did you make sure to first build the project by passing `-b`? See https://github.com/nuxt-community/nuxt-generate-cluster#command-line-options

**Comment by kyrsquir** [comment]
> Did you make sure to first build the project by passing `-b`

Thanks, that worked and went almost 3 times faster! I would probably mention/rephrase in the docs that it differs from `nuxt generate` in that it doesn't build the project by default.

I'm getting a lot of `Payload-extractor had to duplicate some nested routes data in extracted payload` messages during the process, could you please elaborate a bit on this message and its impact on build time and size?

**Comment by pimlie** [comment]
The `Payload-extractor had to duplicate some nested routes data in extracted payload` msg is not a message I recognize, afaik it isnt logged from this package or by Nuxt.js itself?

**Comment by kyrsquir** [comment]
Right, sorry, forgot to mention that I'm also using [nuxt payload extractor](https://github.com/dreaMinder/nuxt-payload-extractor). The fact is that with regular `nuxt generate` I'm not getting any messages like these. Updated original post with full code of my `routes()` in case that helps.

I suspect that this other repo is a better place to report and discuss this. Please confirm.

**Comment by pimlie** [comment]
I think its indeed better to ask in the payload extractor repo, looking at their code it isnt immediately clear to me what could be going wrong. But even after looking at the code I still dont understand what they are trying to convey with that message.

**Comment by kyrsquir** [comment]
Ok will do, thanks.
