### ISSUE TITLE
Doesn't work with the sitemap module

### ISSUE THREAD

**Issue by isokosan** [nuxt-community/nuxt-generate-cluster#29]
My sitemap isn't being generated after switching to generate cluster. Is it because this module doesn't emit the `generate:done` event that the sitemap module listens to? 

```
  // On "generate" mode, generate static files for each sitemap or sitemapindex
  nuxtInstance.nuxt.hook('generate:done', async () => {
    logger.info('Generating sitemaps')
    await Promise.all(options.map((options) => generateSitemaps(options, globalCache, nuxtInstance)))
  })
```

**Comment by simplenotezy** [comment]
See https://github.com/nuxt-community/nuxt-generate-cluster/issues/20 not sure if it would help you @isokosan

**Comment by isokosan** [comment]
Yes, using the `callHook` from `nuxt` as below did fix the issue. Thanks a lot @simplenotezy!
