### ISSUE TITLE
Increase build speed, 

### ISSUE THREAD

**Issue by simplenotezy** [nuxt-community/nuxt-generate-cluster#31]
As suggested by @manniL, you can play with theese configurations: https://nuxtjs.org/api/configuration-build#parallel, https://nuxtjs.org/api/configuration-build#cache and https://nuxtjs.org/api/configuration-build#hardsource.

Will these still work with the generate cluster package, or does the generate cluster package already leverage some of these features?

**Comment by pimlie** [comment]
No, building is only done in the master process. So you will indeed need to set those config options if you want to try to speed-up the initial webpack build.

nuxt-**generate**-cluster only helps to speeds-up generating your pages _after_ the buid has finished.

**Comment by simplenotezy** [comment]
OK thanks @pimlie 😊

**Comment by nachoadjust** [comment]
Hello there!

Dumb question here. Would combining these [configurations](https://github.com/nuxt-community/nuxt-generate-cluster/issues/31#issue-648029249) with nuxt-generate-cluster indeed increase the build speed?

Please let me know if I am wrong, but if I understood correctly the best combo would be to:

- Use the configuration setup (parallel, cache, hardsource) to speed up the build process.
- Use nuxt-generate-cluster to speed up the pages generation process.

Is this correct? or did I misunderstood

Thanks!!
