### ISSUE TITLE
Tips to ensure generate process is using all of its resources

### ISSUE THREAD

**Issue by simplenotezy** [nuxt-community/nuxt-generate-cluster#33]
How can I verify that the nuxt generate process is running at it's maximum resources?

Currently testing build times on a DigitalOcean server: `CPU-Optimized / 8 GB / 4 vCPUs` in `nuxt.config.js` I have set it to be 6 workers.

When running a build the load-average is around `2.27, 2.0, 1.36` and threads is around 2-4 running simultaneously, mostly only 2 though.

I am really interesting in know if we're using all the resources that we have at the DO server, and if not, how we can increase the effectivity of the generate process. Currently it takes around 35-40 minutes to perform a build.

**Comment by Spreizu** [comment]
I'm also interested in trying to figure out, whether setting the worker count higher than the thread count actually increases the performance, and if so, then how could I figure out that magic number.

@simplenotezy Regarding the build time, if you're using the latest Nuxt version, I highly recommend that you turn off HTML JavaScript (and CSS, if you're extracting it) minifiers in nuxt.config. As all of the JS is already minified during generate, it is not necessary to try to minify it again inside the HTML (as there should be no JS in the final HTML, unless you're manually inserting it somewhere).
Disabling HTML minifier reduced our projects generate time by 300%.

**Comment by atinux** [comment]
Doing issue triage, please re-open is this is still relevant.
