### ISSUE TITLE
Nuxt build assets not moved from .nuxt to dist folder

### ISSUE THREAD

**Issue by simoneldevig** [nuxt-community/nuxt-generate-cluster#35]
Hi!

I'm experiencing an issue with `2.15.6` where all static assets returns 404 on the statically generated version. The issue seems to be caused by the built assets not being moved from the `.nuxt` folder to the dist folder on `nuxt-generate`.

The current workaround is to manually move the assets in the done callback, but would it possible to add similar behaviour as the `nuxt generate` in regards to building and adding the assets to the dist folder before the SSG starts? :-)

**Comment by simoneldevig** [comment]
Using the `--build` arg solved the issue :-)

**Comment by kovan** [comment]
Yeah, I have been looking at this for a while now, shouldn't this be the default behavior?
