### ISSUE TITLE
[Question] Generating static sites on-demand with Nuxt.js

### ISSUE THREAD

**Issue by jameswragg** [nuxt-community/nuxt-generate-cluster#9]
Cross-post from [nuxt.js/issues/#2370](https://github.com/nuxt/nuxt.js/issues/2370) but this repo also seems applicable…

---

Hi, I'm trying to create a static-site on-demand API using hapi.js to power the API & nuxt.js as the static-site generator but hitting some blockers….

Here's my setup:

1. The API takes a POST payload
2. Based on the payload the API dynamically creates the `generate.routes` array (passing payloads in for each route)
3. Calls `generate()` to create the static site in `./dist`

Issue:

This API is potentially going to be hammered - building a lot of individual content pages and pushing them to S3 buckets. All generated sites going to the `./dist` directory is a problem - I currently have an `isGenerating` flag to prevent multiple generate calls, forcing the client to re-try the API.
1. Is using Nuxt as a static-site generator on-demand a ridiculous idea?
2. If (hopefully) not, are there ways of managing the output better. Potentially streaming straight to an S3 bucket?
3. Should the generator be able to handle parallel builds?

Thanks in advance,
James

**Comment by pimlie** [comment]
Lets have the discussion on nuxt's issues as thats probably more helpful for others.
